"""add parent access and appointments

Revision ID: 87518c6eebb8
Revises: ed2b53c79584
Create Date: 2026-08-26 10:45:37.665828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87518c6eebb8'
down_revision = 'ed2b53c79584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('school_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('booking_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('parent_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','closed','cancelled')", name='ck_appointment_event_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_event_school_year'), ['school_year'], unique=False)

    op.create_table('appointment_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('public_label', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appointment_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.CheckConstraint("status IN ('available','blocked','cancelled')", name='ck_appointment_slot_status'),
    sa.CheckConstraint('capacity > 0', name='ck_appointment_slot_capacity'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_appointment_slot_period'),
    sa.ForeignKeyConstraint(['event_id'], ['appointment_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['appointment_resource.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'starts_at', 'ends_at', name='uq_slot_resource_period')
    )
    with op.batch_alter_table('appointment_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_slot_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_slot_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_slot_starts_at'), ['starts_at'], unique=False)

    op.create_table('parent_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('security_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','active','locked','revoked')", name='ck_parent_access_status'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schueler_id', 'email_normalized', name='uq_parent_access_student_email')
    )
    with op.batch_alter_table('parent_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_access_schueler_id'), ['schueler_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_access_status'), ['status'], unique=False)

    op.create_table('activation_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('parent_access_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('first_access','second_access')", name='ck_activation_grant_purpose'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_access_id'], ['parent_access.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('activation_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activation_grant_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activation_grant_schueler_id'), ['schueler_id'], unique=False)

    op.create_table('appointment_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('parent_access_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('confirmed','cancelled','attended','no_show')", name='ck_appointment_booking_status'),
    sa.ForeignKeyConstraint(['event_id'], ['appointment_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_access_id'], ['parent_access.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slot.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_booking_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_booking_schueler_id'), ['schueler_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_booking_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_booking_status'), ['status'], unique=False)

    op.create_table('parent_login_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_access_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('login','confirm_email')", name='ck_parent_login_token_purpose'),
    sa.ForeignKeyConstraint(['parent_access_id'], ['parent_access.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('parent_login_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_login_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_login_token_parent_access_id'), ['parent_access_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_login_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_login_token_parent_access_id'))
        batch_op.drop_index(batch_op.f('ix_parent_login_token_expires_at'))

    op.drop_table('parent_login_token')
    with op.batch_alter_table('appointment_booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_booking_status'))
        batch_op.drop_index(batch_op.f('ix_appointment_booking_slot_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_booking_schueler_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_booking_event_id'))

    op.drop_table('appointment_booking')
    with op.batch_alter_table('activation_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activation_grant_schueler_id'))
        batch_op.drop_index(batch_op.f('ix_activation_grant_expires_at'))

    op.drop_table('activation_grant')
    with op.batch_alter_table('parent_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_access_status'))
        batch_op.drop_index(batch_op.f('ix_parent_access_schueler_id'))

    op.drop_table('parent_access')
    with op.batch_alter_table('appointment_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_slot_starts_at'))
        batch_op.drop_index(batch_op.f('ix_appointment_slot_resource_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_slot_event_id'))

    op.drop_table('appointment_slot')
    op.drop_table('appointment_resource')
    with op.batch_alter_table('appointment_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_event_school_year'))

    op.drop_table('appointment_event')
    # ### end Alembic commands ###
