"""baseline existing schema

Revision ID: ed2b53c79584
Revises: 
Create Date: 2026-08-26 10:08:53.059653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2b53c79584'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('einschulungsjahr', sa.Integer(), nullable=True),
    sa.Column('frist_aosf', sa.Date(), nullable=True),
    sa.Column('anzahl_klassen', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schueler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('geschlecht', sa.String(length=10), nullable=True),
    sa.Column('kita', sa.String(length=200), nullable=True),
    sa.Column('kann_kind', sa.Boolean(), nullable=True),
    sa.Column('diag_status', sa.String(length=20), nullable=True),
    sa.Column('diag_ergebnis', sa.Text(), nullable=True),
    sa.Column('arzt_status', sa.String(length=20), nullable=True),
    sa.Column('arzt_bemerkung', sa.Text(), nullable=True),
    sa.Column('ogs_anmeldung', sa.Boolean(), nullable=True),
    sa.Column('schulspiel_status', sa.String(length=20), nullable=True),
    sa.Column('freund1_id', sa.Integer(), nullable=True),
    sa.Column('freund1_negativ', sa.Boolean(), nullable=True),
    sa.Column('freund2_id', sa.Integer(), nullable=True),
    sa.Column('freund2_negativ', sa.Boolean(), nullable=True),
    sa.Column('freunde_bemerkung', sa.Text(), nullable=True),
    sa.Column('keine_freunde', sa.Boolean(), nullable=True),
    sa.Column('klasse', sa.String(length=10), nullable=True),
    sa.Column('betreuung', sa.String(length=20), nullable=True),
    sa.Column('foerderkurs_lrs', sa.Boolean(), nullable=True),
    sa.Column('foerderkurs_mathe', sa.Boolean(), nullable=True),
    sa.Column('foerderkurs_sport', sa.Boolean(), nullable=True),
    sa.Column('foerderkurs_deutsch', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['freund1_id'], ['schueler.id'], ),
    sa.ForeignKeyConstraint(['freund2_id'], ['schueler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('aosf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('leitung_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('bericht_medizin_dateiname', sa.String(length=255), nullable=True),
    sa.Column('bericht_therapie_dateiname', sa.String(length=255), nullable=True),
    sa.Column('konferenz_datum', sa.Date(), nullable=True),
    sa.Column('konferenz_ergebnis', sa.String(length=50), nullable=True),
    sa.Column('antrag_datum', sa.Date(), nullable=True),
    sa.Column('antrag_dateiname', sa.String(length=255), nullable=True),
    sa.Column('schulamt_datum', sa.Date(), nullable=True),
    sa.Column('schulamt_entscheidung', sa.String(length=50), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['leitung_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('wortschatz', sa.Integer(), nullable=True),
    sa.Column('grammatik', sa.Integer(), nullable=True),
    sa.Column('aussprache', sa.Integer(), nullable=True),
    sa.Column('gespraechsverhalten', sa.Integer(), nullable=True),
    sa.Column('saetze_nachsprechen', sa.Integer(), nullable=True),
    sa.Column('reimen', sa.Integer(), nullable=True),
    sa.Column('pluralbildung', sa.Integer(), nullable=True),
    sa.Column('woerter_segmentieren', sa.Integer(), nullable=True),
    sa.Column('mengenerfassung', sa.Integer(), nullable=True),
    sa.Column('menge_herstellen', sa.Integer(), nullable=True),
    sa.Column('zahlen_erkennen', sa.Integer(), nullable=True),
    sa.Column('rueckwaerts_zaehlen', sa.Integer(), nullable=True),
    sa.Column('zahlreihe_erzeugen', sa.Integer(), nullable=True),
    sa.Column('logische_reihe', sa.Integer(), nullable=True),
    sa.Column('bild_malen', sa.Integer(), nullable=True),
    sa.Column('komplexe_figur', sa.Integer(), nullable=True),
    sa.Column('gesamteindruck_kognitiv', sa.Integer(), nullable=True),
    sa.Column('gesamteindruck_verhalten', sa.Integer(), nullable=True),
    sa.Column('aosf_verdacht', sa.Boolean(), nullable=True),
    sa.Column('rueckstellung_empfohlen', sa.Boolean(), nullable=True),
    sa.Column('pdf_dateiname', sa.String(length=255), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('schulspiel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kita_bericht',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('kognitiv', sa.Integer(), nullable=True),
    sa.Column('verhalten', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rueckstellung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('leitung_user_id', sa.Integer(), nullable=True),
    sa.Column('bericht_medizin_dateiname', sa.String(length=255), nullable=True),
    sa.Column('bericht_therapie_dateiname', sa.String(length=255), nullable=True),
    sa.Column('konferenz_datum', sa.Date(), nullable=True),
    sa.Column('konferenz_ergebnis', sa.String(length=50), nullable=True),
    sa.Column('elternschreiben_datum', sa.Date(), nullable=True),
    sa.Column('elternschreiben_dateiname', sa.String(length=255), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['leitung_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schulaerztliche_untersuchung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('hoerfaehigkeit', sa.String(length=50), nullable=True),
    sa.Column('sehfaehigkeit', sa.String(length=50), nullable=True),
    sa.Column('haendigkeit', sa.String(length=20), nullable=True),
    sa.Column('erstsprache', sa.String(length=100), nullable=True),
    sa.Column('ergebnis', sa.String(length=100), nullable=True),
    sa.Column('foerder_grobmotorik', sa.Boolean(), nullable=True),
    sa.Column('foerder_fein_visuomotorik', sa.Boolean(), nullable=True),
    sa.Column('foerder_visuelle_wahrnehmung', sa.Boolean(), nullable=True),
    sa.Column('foerder_auditive_wahrnehmung', sa.Boolean(), nullable=True),
    sa.Column('foerder_deutschkenntnisse', sa.Boolean(), nullable=True),
    sa.Column('foerder_zahlen_mengen', sa.Boolean(), nullable=True),
    sa.Column('foerder_konzentration', sa.Boolean(), nullable=True),
    sa.Column('foerder_psychosozial', sa.Boolean(), nullable=True),
    sa.Column('foerder_sprache', sa.String(length=200), nullable=True),
    sa.Column('aosf_verdacht', sa.Boolean(), nullable=True),
    sa.Column('pdf_dateiname', sa.String(length=255), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('gesamteinschaetzung', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schulspiel_diagnostik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('aufgabenverstaendnis', sa.Integer(), nullable=True),
    sa.Column('konzentration', sa.Integer(), nullable=True),
    sa.Column('anstrengungsbereitschaft', sa.Integer(), nullable=True),
    sa.Column('merkfaehigkeit', sa.Integer(), nullable=True),
    sa.Column('ausdauer', sa.Integer(), nullable=True),
    sa.Column('selbstbewusstsein', sa.Integer(), nullable=True),
    sa.Column('kontaktfaehigkeit', sa.Integer(), nullable=True),
    sa.Column('regelverhalten', sa.Integer(), nullable=True),
    sa.Column('versteht_anweisungen', sa.Integer(), nullable=True),
    sa.Column('ausdruck_altersangemessen', sa.Integer(), nullable=True),
    sa.Column('vollstaendige_saetze', sa.Integer(), nullable=True),
    sa.Column('richtige_verbformen', sa.Integer(), nullable=True),
    sa.Column('richtige_artikel', sa.Integer(), nullable=True),
    sa.Column('konzept_von_schrift', sa.Integer(), nullable=True),
    sa.Column('schreibt_eigenen_namen', sa.Integer(), nullable=True),
    sa.Column('koerperkoordination', sa.Integer(), nullable=True),
    sa.Column('fingerkoordination', sa.Integer(), nullable=True),
    sa.Column('farben_und_formen', sa.Integer(), nullable=True),
    sa.Column('figur_grund_wahrnehmung', sa.Integer(), nullable=True),
    sa.Column('mengeninvarianz', sa.Integer(), nullable=True),
    sa.Column('kognition', sa.Integer(), nullable=True),
    sa.Column('raum_lage_beziehung', sa.Integer(), nullable=True),
    sa.Column('auditive_wahrnehmung', sa.Integer(), nullable=True),
    sa.Column('silben_segmentieren', sa.Integer(), nullable=True),
    sa.Column('reime_erkennen', sa.Integer(), nullable=True),
    sa.Column('gesamtwert', sa.Integer(), nullable=True),
    sa.Column('pdf_dateiname', sa.String(length=255), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schulspiel_diagnostik')
    op.drop_table('schulaerztliche_untersuchung')
    op.drop_table('rueckstellung')
    op.drop_table('kita_bericht')
    op.drop_table('diagnostik')
    op.drop_table('aosf')
    op.drop_table('user')
    op.drop_table('schueler')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
